### ISSUE TITLE
Sprint Review

### ISSUE THREAD

**Issue by Pinestorm** [flock-skate/Flock-app#10]
Progress so far:

The team has completed the Web Ap UX. All team members successfully completed their sprints and got everything into the presentation.

**Comment by Pinestorm** [comment]
The sprint succeeded at keeping the team on track with all the components we had to complete. The team worked well and got every task completed. Some things that could be worked on in the future would be to close the sprints as soon as they are done and to communicate a bit better with the team to say whether someone has completed something so that we aren't wondering last minute.

**Comment by zama0023** [comment]
Team was on task and everything was done properly in a timely manner.

**Comment by oryn** [comment]
Team worked well together and assigned tasks appropriate to our skills and finished said tasks smoothly.

**Comment by Dustin-L** [comment]
Individual tasks were assigned and all were completed on time. Can't pinpoint anything to critique.

**Comment by Pinestorm** [comment]
@thomasjbradley

**Comment by thomasjbradley** [comment]
:boom:
